// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using dotNetProjekt;

namespace dotNetProjekt.Migrations
{
    [DbContext(typeof(MainWindow.EmploeeContext))]
    partial class EmploeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("dotNetProjekt.Pracownicy", b =>
                {
                    b.Property<int>("PracownicyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adres");

                    b.Property<string>("Email");

                    b.Property<string>("Imie");

                    b.Property<string>("Nazwisko");

                    b.Property<int>("NumerTelefonu");

                    b.Property<string>("Stanowisko");

                    b.HasKey("PracownicyId");

                    b.ToTable("pracownicies");
                });
#pragma warning restore 612, 618
        }
    }
}
